### ISSUE TITLE
Include wait_for_update on the setDefaultConsent Call

### ISSUE THREAD

**Issue by lanzone1** [MyAgilePrivacy/gtm-templates-myagileprivacy-cmp#1]
When reviewing your template we've noticed that the `setDefaultConsentState` call does not include the [wait_for_update](https://developers.google.com/tag-platform/tag-manager/templates/api#setdefaultconsentstate) option. This is required for any asynchronous consent management script load to delay tag execution.

**Comment by MyAgilePrivacy** [comment]
Hello, thank you for your code review. 
This problem has been fixed with our latest template update.

**Comment by lanzone1** [comment]
Thanks for the prompt reply. Your template calls the API `setDefaultConsentState` in two places, but only one was updated. The call that uses `getConsentRegionData` still does not include the `wait_for_update` option.

**Comment by MyAgilePrivacy** [comment]
You are welcome. With our latest release, we fixed also this issue. Thank you!
